
export type ThemeMode = 'light' | 'dark';
export type ThemeVars = {
    [key: string]: string;
}

export type ThemePalettes = {
    [paletteName: string]: {
        [mode in ThemeMode]: ThemeVars;
    };
  };
export const themePalettes = {
    default: {
        light: {
            '--background': '#F9FAFB',
            '--foreground': '#111827',
            '--card': '#FFFFFF',
            '--accent': '#10B981',
            '--accent-hover': '#059669',
            '--accent-bg': '#D1FAE5',
            '--border': '#E5E7EB',
            '--error': '#EF4444',
            '--success': '#22C55E',
            '--warning': '#F59E0B',
            '--bg-color': '#f8fafc',
            '--border-color': '#cbd5e1',
            '--hover-color': '#e2e8f0',
            '--today-highlight': '#6366f1',
            '--event-bg': '#06b6d4',
            '--event-text': '#0f172a',
        },
        dark: {
            '--background': '#0F172A',
            '--foreground': '#F8FAFC',
            '--card': '#1E293B',
            '--accent': '#34D399',
            '--accent-hover': '#10B981',
            '--accent-bg': '#064E3B',
            '--border': '#334155',
            '--error': '#F87171',
            '--success': '#4ADE80',
            '--warning': '#FBBF24',
            '--bg-color': '#0f172a',
            '--border-color': '#475569',
            '--hover-color': '#334155',
            '--today-highlight': '#818cf8',
            '--event-bg': '#22d3ee',
            '--event-text': '#f8fafc',
        },
    },
    ocean: {
        light: {
            '--background': '#E0F7FA',
            '--foreground': '#004D40',
            '--card': '#FFFFFF',
            '--accent': '#00BCD4',
            '--accent-hover': '#0097A7',
            '--accent-bg': '#B2EBF2',
            '--border': '#B2DFDB',
            '--error': '#FF5252',
            '--success': '#4CAF50',
            '--warning': '#FFC107',
            '--bg-color': '#E0F2F1',
            '--border-color': '#80CBC4',
            '--hover-color': '#B2DFDB',
            '--today-highlight': '#26C6DA',
            '--event-bg': '#00ACC1',
            '--event-text': '#004D40',
        },
        dark: {
            '--background': '#004D40',
            '--foreground': '#E0F2F1',
            '--card': '#00695C',
            '--accent': '#00E5FF',
            '--accent-hover': '#00B8D4',
            '--accent-bg': '#00363A',
            '--border': '#00796B',
            '--error': '#FF8A80',
            '--success': '#69F0AE',
            '--warning': '#FFD54F',
            '--bg-color': '#00363A',
            '--border-color': '#004D40',
            '--hover-color': '#00695C',
            '--today-highlight': '#4DD0E1',
            '--event-bg': '#00B8D4',
            '--event-text': '#E0F2F1',
        },
    },
    sunset: {
        light: {
            "--background": "#fff7ed",
            "--foreground": "#7c2d12",
            "--card": "#ffffff",
            "--accent": "#fb923c",
            "--accent-hover": "#f97316",
            "--accent-bg": "#ffedd5",
            "--border": "#fed7aa",
            "--error": "#f87171",
            "--success": "#4ade80",
            "--warning": "#facc15",
            "--bg-color": "#fffbeb",
            "--border-color": "#fcd34d",
            "--hover-color": "#fef3c7",
            "--today-highlight": "#f97316",
            "--event-bg": "#fdba74",
            "--event-text": "#7c2d12"
        },
        dark: {
            "--background": "#7c2d12",
            "--foreground": "#fff7ed",
            "--card": "#9a3412",
            "--accent": "#fb923c",
            "--accent-hover": "#fdba74",
            "--accent-bg": "#3b0d03",
            "--border": "#ea580c",
            "--error": "#f87171",
            "--success": "#4ade80",
            "--warning": "#fcd34d",
            "--bg-color": "#3b0d03",
            "--border-color": "#7c2d12",
            "--hover-color": "#9a3412",
            "--today-highlight": "#fdba74",
            "--event-bg": "#fb923c",
            "--event-text": "#fff7ed"
        }
    },
    grape: {
        light: {
            "--background": "#f3e8ff",
            "--foreground": "#4b0082",
            "--card": "#ffffff",
            "--accent": "#a855f7",
            "--accent-hover": "#9333ea",
            "--accent-bg": "#ede9fe",
            "--border": "#ddd6fe",
            "--error": "#f87171",
            "--success": "#4ade80",
            "--warning": "#facc15",
            "--bg-color": "#faf5ff",
            "--border-color": "#c4b5fd",
            "--hover-color": "#ede9fe",
            "--today-highlight": "#c084fc",
            "--event-bg": "#a78bfa",
            "--event-text": "#4b0082"
        },
        dark: {
            "--background": "#4b0082",
            "--foreground": "#f3e8ff",
            "--card": "#5b21b6",
            "--accent": "#c084fc",
            "--accent-hover": "#a855f7",
            "--accent-bg": "#2e1065",
            "--border": "#6b21a8",
            "--error": "#f87171",
            "--success": "#4ade80",
            "--warning": "#fcd34d",
            "--bg-color": "#2e1065",
            "--border-color": "#5b21b6",
            "--hover-color": "#6b21a8",
            "--today-highlight": "#a855f7",
            "--event-bg": "#c084fc",
            "--event-text": "#f3e8ff"
        }
    },
    forest: {
        light: {
            '--background': '#E6F2E6',
            '--foreground': '#2F4F2F',
            '--card': '#FFFFFF',
            '--accent': '#3CB371',
            '--accent-hover': '#2E8B57',
            '--accent-bg': '#C1E1C1',
            '--border': '#A9D0A9',
            '--error': '#E57373',
            '--success': '#4CAF50',
            '--warning': '#FFD54F',
            '--bg-color': '#E6F2E6',
            '--border-color': '#8FBC8F',
            '--hover-color': '#C1E1C1',
            '--today-highlight': '#4CAF50',
            '--event-bg': '#3CB371',
            '--event-text': '#2F4F2F',
        },
        dark: {
            '--background': '#2F4F2F',
            '--foreground': '#E6F2E6',
            '--card': '#1B3621',
            '--accent': '#66BB6A',
            '--accent-hover': '#4CAF50',
            '--accent-bg': '#254C24',
            '--border': '#3A6F3A',
            '--error': '#EF9A9A',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#254C24',
            '--border-color': '#3A6F3A',
            '--hover-color': '#3A6F3A',
            '--today-highlight': '#81C784',
            '--event-bg': '#4CAF50',
            '--event-text': '#E6F2E6',
        },
    },

    lavender: {
        light: {
            '--background': '#F3E8FF',
            '--foreground': '#4B0082',
            '--card': '#FFFFFF',
            '--accent': '#B57EDC',
            '--accent-hover': '#9161C4',
            '--accent-bg': '#E6DAF7',
            '--border': '#D1B3FF',
            '--error': '#F87171',
            '--success': '#4ADE80',
            '--warning': '#FACC15',
            '--bg-color': '#F9F5FF',
            '--border-color': '#C4B5FD',
            '--hover-color': '#E6DAF7',
            '--today-highlight': '#B57EDC',
            '--event-bg': '#9161C4',
            '--event-text': '#4B0082',
        },
        dark: {
            '--background': '#4B0082',
            '--foreground': '#F3E8FF',
            '--card': '#5B21B6',
            '--accent': '#B57EDC',
            '--accent-hover': '#9161C4',
            '--accent-bg': '#2E1065',
            '--border': '#6B21A8',
            '--error': '#F87171',
            '--success': '#4ADE80',
            '--warning': '#FCD34D',
            '--bg-color': '#2E1065',
            '--border-color': '#5B21B6',
            '--hover-color': '#6B21A8',
            '--today-highlight': '#B57EDC',
            '--event-bg': '#9161C4',
            '--event-text': '#F3E8FF',
        },
    },

    sunrise: {
        light: {
            '--background': '#FFF8E1',
            '--foreground': '#5D4037',
            '--card': '#FFFFFF',
            '--accent': '#FF7043',
            '--accent-hover': '#F4511E',
            '--accent-bg': '#FFE0B2',
            '--border': '#FFCCBC',
            '--error': '#E57373',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#FFF3E0',
            '--border-color': '#FFAB91',
            '--hover-color': '#FFE0B2',
            '--today-highlight': '#FF7043',
            '--event-bg': '#F4511E',
            '--event-text': '#5D4037',
        },
        dark: {
            '--background': '#5D4037',
            '--foreground': '#FFF8E1',
            '--card': '#3E2723',
            '--accent': '#FF8A65',
            '--accent-hover': '#FF7043',
            '--accent-bg': '#2F1B16',
            '--border': '#6D4C41',
            '--error': '#EF9A9A',
            '--success': '#A5D6A7',
            '--warning': '#FFD54F',
            '--bg-color': '#2F1B16',
            '--border-color': '#6D4C41',
            '--hover-color': '#6D4C41',
            '--today-highlight': '#FF8A65',
            '--event-bg': '#FF7043',
            '--event-text': '#FFF8E1',
        },
    },
    cocoa: {
        light: {
            '--background': '#F5EFE6',
            '--foreground': '#4B3B2B',
            '--card': '#FFFFFF',
            '--accent': '#A9746E',
            '--accent-hover': '#8B5E3C',
            '--accent-bg': '#EBD9C6',
            '--border': '#C9B69A',
            '--error': '#E57373',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#F7F1E1',
            '--border-color': '#BFA982',
            '--hover-color': '#EBD9C6',
            '--today-highlight': '#A9746E',
            '--event-bg': '#8B5E3C',
            '--event-text': '#4B3B2B',
        },
        dark: {
            '--background': '#4B3B2B',
            '--foreground': '#F5EFE6',
            '--card': '#6B5B4B',
            '--accent': '#C4A484',
            '--accent-hover': '#A9746E',
            '--accent-bg': '#3E2F1F',
            '--border': '#7B6A5D',
            '--error': '#EF9A9A',
            '--success': '#A5D6A7',
            '--warning': '#FFD54F',
            '--bg-color': '#3E2F1F',
            '--border-color': '#6B5B4B',
            '--hover-color': '#7B6A5D',
            '--today-highlight': '#C4A484',
            '--event-bg': '#A9746E',
            '--event-text': '#F5EFE6',
        },
    },

    teal: {
        light: {
            '--background': '#E0F2F1',
            '--foreground': '#004D40',
            '--card': '#FFFFFF',
            '--accent': '#009688',
            '--accent-hover': '#00796B',
            '--accent-bg': '#B2DFDB',
            '--border': '#80CBC4',
            '--error': '#E57373',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#E0F7FA',
            '--border-color': '#4DB6AC',
            '--hover-color': '#B2DFDB',
            '--today-highlight': '#00796B',
            '--event-bg': '#004D40',
            '--event-text': '#E0F2F1',
        },
        dark: {
            '--background': '#004D40',
            '--foreground': '#E0F2F1',
            '--card': '#00695C',
            '--accent': '#4DB6AC',
            '--accent-hover': '#009688',
            '--accent-bg': '#00332F',
            '--border': '#00796B',
            '--error': '#EF9A9A',
            '--success': '#A5D6A7',
            '--warning': '#FFD54F',
            '--bg-color': '#00332F',
            '--border-color': '#004D40',
            '--hover-color': '#00695C',
            '--today-highlight': '#4DB6AC',
            '--event-bg': '#009688',
            '--event-text': '#E0F2F1',
        },
    },

    ember: {
        light: {
            '--background': '#FFF3F0',
            '--foreground': '#7B241C',
            '--card': '#FFFFFF',
            '--accent': '#E74C3C',
            '--accent-hover': '#C0392B',
            '--accent-bg': '#FADBD8',
            '--border': '#F5B7B1',
            '--error': '#E57373',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#FFF0EB',
            '--border-color': '#E74C3C',
            '--hover-color': '#FADBD8',
            '--today-highlight': '#C0392B',
            '--event-bg': '#E74C3C',
            '--event-text': '#7B241C',
        },
        dark: {
            '--background': '#7B241C',
            '--foreground': '#FFF3F0',
            '--card': '#641E16',
            '--accent': '#EC7063',
            '--accent-hover': '#E74C3C',
            '--accent-bg': '#4A1A14',
            '--border': '#922B21',
            '--error': '#EF9A9A',
            '--success': '#A5D6A7',
            '--warning': '#FFD54F',
            '--bg-color': '#4A1A14',
            '--border-color': '#641E16',
            '--hover-color': '#922B21',
            '--today-highlight': '#EC7063',
            '--event-bg': '#E74C3C',
            '--event-text': '#FFF3F0',
        },
    },

    plum: {
        light: {
            '--background': '#F8F0FC',
            '--foreground': '#4B0082',
            '--card': '#FFFFFF',
            '--accent': '#9B59B6',
            '--accent-hover': '#8E44AD',
            '--accent-bg': '#E9D7F5',
            '--border': '#D7BDE2',
            '--error': '#E57373',
            '--success': '#81C784',
            '--warning': '#FFD54F',
            '--bg-color': '#F4E8F9',
            '--border-color': '#B795C9',
            '--hover-color': '#E9D7F5',
            '--today-highlight': '#8E44AD',
            '--event-bg': '#9B59B6',
            '--event-text': '#4B0082',
        },
        dark: {
            '--background': '#4B0082',
            '--foreground': '#F8F0FC',
            '--card': '#5B297D',
            '--accent': '#B399D4',
            '--accent-hover': '#9B59B6',
            '--accent-bg': '#2F1D4D',
            '--border': '#6A4C8B',
            '--error': '#EF9A9A',
            '--success': '#A5D6A7',
            '--warning': '#FFD54F',
            '--bg-color': '#2F1D4D',
            '--border-color': '#5B297D',
            '--hover-color': '#6A4C8B',
            '--today-highlight': '#B399D4',
            '--event-bg': '#9B59B6',
            '--event-text': '#F8F0FC',
        },
      },
};
